Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"

    # HSTS Server 1
    config.vm.define "serverA" do |serverA|
      serverA.vm.hostname = "serverA"
      serverA.vm.network "private_network", ip: "192.168.56.10" 
      serverA.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
      serverA.vm.provider "virtualbox" do |vb|
        vb.memory = 3919
        vb.cpus = 2
      end
    end 

    # HSTS Server 2
    config.vm.define "serverB" do |serverB|
      serverB.vm.hostname = "serverB"
      serverB.vm.network "private_network", ip: "192.168.56.11"  
      serverB.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
      serverB.vm.provider "virtualbox" do |vb|
        vb.memory = 3919
        vb.cpus = 2
      end
    end
  end
    