- name: Copy aspera configuration template
  ansible.builtin.copy:
    src: ./files/aspera.conf 
    dest: /opt/aspera/etc/aspera.conf
    owner: asperadaemon
    group: aspadmins
    mode: '0755' 

- name: Restart Aspera
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - asperanoded
    - asperacentral