---
# tasks file for configure-aspera 
- name: Configure Aspera license
  import_tasks: configure-license.yml

- name: Configure host services
  import_tasks: configure-services.yml

- name: Configure firewall
  import_tasks: configure-firewall.yml

- name: Configure ssh server
  import_tasks: configure-ssh.yml

- name: Configure aspera user
  import_tasks: configure-asperauser.yml

- name: Configure  Aspera configuration
  import_tasks: configure-asperaconfiguration.yml 

- name: Start sync on asperaContent folder
  ansible.builtin.command: "async -N asyncTwoWay -w asperaPassword123 -d /home/asperauser/asperaContent -r asperauser@192.168.56.11:/ -l 10M -a fair -g 1M -G 1M -C -K BIDI" 
  async: 1000
  poll: 0
  when:
    - ('primary' in group_names)
    - runAsperaSync is true  